# Generated by Django 5.0.1 on 2024-04-03 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_rename_tilte_expense_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('amount', models.PositiveIntegerField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('category', models.CharField(choices=[('salary', 'salary'), ('buisness', 'buisness'), ('investment', 'investment'), ('rental', 'rental'), ('interest', 'interest'), ('dividend', 'dividend'), ('royalty', 'royalty'), ('capital', 'capital'), ('pension', 'pension'), ('socialsecurity', 'socialsecurity')], default='salary', max_length=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
